services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.production
    ports:
      - "3000:3000"
    volumes:
      - ./cookies.txt:/app/cookies.txt
    restart: unless-stopped
